; ; PlatformIO Project Configuration File
; ;
; ;   Build options: build flags, source filter
; ;   Upload options: custom upload port, speed and extra flags
; ;   Library options: dependencies, extra library storages
; ;   Advanced options: extra scripting
; ;
; ; Please visit documentation for the other options and examples
; ; https://docs.platformio.org/page/projectconf.html

; [env:node32s]
; platform = espressif32
; board = node32s
; framework = arduino
; monitor_speed = 115200
; upload_speed = 921600

; lib_deps =
;     GyverOLED
;     madhephaestus/ESP32Servo@^3.0.5
;     Wire
;     pololu/VL53L0X@^1.3.1
;     lib/ZebraTOF
;     adafruit/Adafruit TCS34725 @ ^1.4.0
;     https://github.com/jrowberg/i2cdevlib.git
    
    

; ; Make sure linker looks inside lib/ZebraScreen
; build_flags = -Llib/ZebraScreen/src -lzebrascreen
;             ;   -Llib/SMotor2/src -lsmotor2
;               -Llib/SMotorPair/src -lsmotorpair
;             ;   -Llib/ZebraServo -lzebraservo
;               -DARDUINO=10805
;               -Llib/ZebraTOF
;               -Wl,--whole-archive -lZebraTOF -Wl,--no-whole-archive
;               -Llib/ZebraColour/src -lzebracolour
;               -Llib/ZebraGyro/src -lzebragyro

; lib_ldf_mode = deep+

; extra_scripts = pre:extra_script.py





[env:node32s]
platform = espressif32
board = node32s
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    GyverOLED
    madhephaestus/ESP32Servo@^3.0.5
    pololu/VL53L0X@^1.3.1
    lib/ZebraTOF
    adafruit/Adafruit TCS34725 @ ^1.4.0
    jrowberg/I2Cdevlib-MPU6050
    jrowberg/I2Cdevlib-Core
    https://github.com/HuskyLens/HUSKYLENSArduino.git
    ; Remove "Wire" from here - it's a built-in library

; Make sure linker looks inside lib/ZebraScreen
build_flags = -Llib/ZebraScreen/src -lzebrascreen
              -Llib/SMotorPair/src -lsmotorpair
              -DARDUINO=10805
              -Llib/ZebraTOF
              -Wl,--whole-archive -lZebraTOF -Wl,--no-whole-archive
              -Llib/ZebraColour/src -lzebracolour
              -Llib/ZebraGyro/src -lzebragyro
              -Llib/ZebraHuskyLens/src -lZebraHuskyLens

lib_ldf_mode = deep+

extra_scripts = pre:extra_script.py

